name: Basic Compile and Assert Tests
on: [push, pull_request]

jobs:
  compile-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make -C c id3v240.a

  runtime-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make -C c/tests run
